# Generated by Django 4.2.29 on 2026-03-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('mechanical', 'Mechanical Design / CAD'), ('electrical', 'Electrical / Electronics'), ('civil', 'Civil / Structural'), ('software', 'Software / Programming'), ('chemical', 'Chemical / Process Engineering'), ('other', 'Other Engineering')], default='other', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Expected budget in KES', max_digits=10)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open - Bids Welcome'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachments_note', models.TextField(blank=True, help_text='Describe any files you plan to attach', null=True)),
            ],
            options={
                'verbose_name': 'Engineering Task',
                'verbose_name_plural': 'Engineering Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
